# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: synthea
      type: github
      endpoint: science-automation
      name: synthetichealth/synthea
    - repository: synthea-international
      type: github
      endpoint: science-automation
      name: synthetichealth/synthea-international

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: synthea
- checkout: synthea-international
- script: |
    sudo rpm --import http://repos.azul.com/azul-repo.key
    sudo curl http://repos.azul.com/azure-only/zulu-azure.repo -o /etc/yum.repos.d/zulu-azure.repo
    sudo yum -q -y update
    sudo yum -q -y install zulu-11-azure-jdk
  displayName: 'Install JDK 11'
- script: |
    echo $LANG
    cd /home/vsts/work/1/s/synthea
    cp -R ../synthea-international/fi/* .
    export GRADLE_OPTS="-Dfile.encoding=UTF-8"
    ./gradlew build -x test
    javac -version
    java -version
    which java
  displayName: 'Build Synthea for country'
- script: |
    cd /home/vsts/work/1/s/synthea
    export GRADLE_OPTS="-Dfile.encoding=UTF-8"
    ./run_synthea -p 5 "Uusimaa"
  displayName: 'Run synthea for country'
