# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: synthea
      type: github
      endpoint: science-automation
      name: synthetichealth/synthea
    - repository: synthea-international
      type: github
      endpoint: science-automation
      name: synthetichealth/synthea-international

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: synthea
- checkout: synthea-international
- script: |
    cd /home/vsts/work/1/s/synthea
    # temp file some values in synthea.properties
    echo "exporter.encoding = UTF-8" >> ../synthea-international/fi/src/main/resources/synthea.properties
    sed -i 'exporter.fhir.export = false/exporter.fhir.export = true/g'../synthea-international/fi/src/main/resources/synthea.properties
    sed -i 'exporter.hospital.fhir.export = false/exporter.hospital.fhir.export = true/g' ../synthea-international/fi/src/main/resources/synthea.properties
    cp -R ../synthea-international/fi/* .
    ./gradlew build -x test
  displayName: 'Build Synthea for country'
- script: |
    cd /home/vsts/work/1/s/synthea
    cp /home/vsts/work/1/s/healthcare-europe-sample/run.sh .
    chmod 755 run.sh
    ./run.sh
    ls output
  displayName: 'Run synthea for country'
