# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: github://synthetichealth/synthea

- checkout: github://synthetichealth/synthea-international

- script: |
    cd synthetichealth/synthea/
    cp -R ../synthea-international/fi/*
    echo "java version"
    java --version
    echo "python version"
    python --version
    echo Now run the build
  displayName: 'Run a multi-line script'
