# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: synthea
      type: github
      endpoint: science-automation
      name: synthetichealth/synthea
    - repository: synthea-international
      type: github
      endpoint: science-automation
      name: synthetichealth/synthea-international

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: synthea
- checkout: synthea-international
- script: |
    pwd
    ls
    cd synthetichealth/synthea/
    cp -R ../synthea-international/fi/* .
    ls
    pwd
    ./gradlew build
  displayName: 'Build Synthea for country'
- script: |
    cd synthetichealth/synthea/
    ./run_synthea -p 5 "Uusimaa"
  displayName: 'Run synthea for country'
- script |
    echo "test"
  displayName: 'Test'
