# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: synthea
      type: github
      endpoint: science-automation
      name: synthetichealth/synthea
    - repository: synthea-international
      type: github
      endpoint: science-automation
      name: synthetichealth/synthea-international
    - repository: healthcare-europe-sample-storage
      type: github
      endpoint: science-automation
      name: science-automation/healthcare-europe-sample-storage

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: synthea
- checkout: synthea-international
- checkout: healthcare-europe-sample-storage
- script: |
    cd /home/vsts/work/1/s/synthea
    # temp file some values in synthea.properties
    echo "exporter.encoding = UTF-8" >> ../synthea-international/fi/src/main/resources/synthea.properties
    sed -i 's/exporter.fhir.export = false/exporter.fhir.export = true/g'../synthea-international/fi/src/main/resources/synthea.properties
    sed -i 's/exporter.hospital.fhir.export = false/exporter.hospital.fhir.export = true/g' ../synthea-international/fi/src/main/resources/synthea.properties
    cp -R ../synthea-international/fi/* .
    ./gradlew build -x test
  displayName: 'Build Synthea for country'
- script: |
    cd /home/vsts/work/1/s/synthea
    # run for base case with all modules
    ./run_synthea -p 100 Uusimma
    cd ./output/csv
    zip ../all_csv.zip *.csv
    cd ../..
    cd ./output/fhir
    zip ../all_fhir.zip *.json
    cd ../..

    for filename in $BASEDIR/build/resources/main/modules/*.json; do
        module=$(basename "$filename" .json)
        rm ./output/csv/*
        rm ./output/fhir/*
        ./run_synthea -p 100 -m $module Uusimma
        cd ./output/csv
        zip ../${module}_csv.zip *.csv
        cd ../..
        cd ./output/fhir
        zip ../${module}_fhir.zip *.json
        cd ../..
    done
  displayName: 'Run synthea for country'
  #- script: |
  #  cd /home/vsts/work/1/s/synthea
  #  mkdir -p ../healthcare-europe-sample-storage/fi
  #  cp output/* ../healthcare-europe-sample-storage/fi
  #  cd ../healthcare-europe-sample-storage
  #  git pull
  #  git config --global user.name "scivm"
  #  git add .
  #  git commit -m "automated run"
  #  git push origin HEAD:master
  #displayName: "Check files into git storage"
