# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: synthea
      type: github
      endpoint: science-automation
      name: synthetichealth/synthea
    - repository: synthea-international
      type: github
      endpoint: science-automation
      name: synthetichealth/synthea-international
    - repository: healthcare-europe-sample-storage
      type: github
      endpoint: science-automation
      name: science-automation/healthcare-europe-sample-storage

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: synthea
- checkout: synthea-international
- checkout: healthcare-europe-sample-storage
- script: |
    cd /home/vsts/work/1/s/synthea
    # temp file some values in synthea.properties
    echo "exporter.encoding = UTF-8" >> ../synthea-international/fi/src/main/resources/synthea.properties
    sed -i 's/exporter.fhir.export = false/exporter.fhir.export = true/g'../synthea-international/fi/src/main/resources/synthea.properties
    sed -i 's/exporter.hospital.fhir.export = false/exporter.hospital.fhir.export = true/g' ../synthea-international/fi/src/main/resources/synthea.properties
    cp -R ../synthea-international/fi/* .
    ./gradlew build -x test
  displayName: 'Build Synthea for country'
- script: |
    cd /home/vsts/work/1/s/synthea
    cp /home/vsts/work/1/s/healthcare-europe-sample/run.sh .
    chmod 755 run.sh
    ./run.sh /home/vsts/work/1/s/synthea
  displayName: 'Run synthea for country'
  - script: |
    cd /home/vsts/work/1/s/synthea
    mkdir -p ../healthcare-europe-sample-storage/$COUNTRY
    cp output/* ../healthcare-europe-sample-storage/$COUNTRY
    cd ../healthcare-europe-sample-storage/$COUNTRY
    git config --global user.name "scivm"
    git add .
    git commit -m "automated run"
    git push origin HEAD:master
  displayName: "Check files into git storage"
